---
kind: pipeline
type: docker
name: default

services:
- name: localstack
  image: localstack/localstack

steps:
- name: hello
  image: busybox
  commands:
  - echo hello world

trigger:
  branch:
  - main
